import { defineConfig } from 'vite'

// Base path for the deployed site. '/' for local dev and the single-file
// artifact build; '/<repo>/' when GitHub Pages serves it from a subpath.
const BASE = process.env.VITE_BASE_PATH || '/'
import react from '@vitejs/plugin-react'

/**
 * Vite plugin: generates sw.js in the build output with hashed asset URLs
 * for offline caching. Data chunks use cache-first; app shell uses network-first.
 */
function generateServiceWorker() {
  return {
    name: 'generate-sw',
    apply: 'build',
    generateBundle(_, bundle) {
      // Collect hashed filenames from the bundle
      const dataChunks = []
      const appShellAssets = []
      const featureChunks = []

      for (const [fileName] of Object.entries(bundle)) {
        const path = BASE + fileName
        if (fileName.match(/^assets\/data-.*\.js$/)) {
          dataChunks.push(path)
        } else if (fileName.match(/^assets\/(index|vendor-react).*\.(js|css)$/)) {
          appShellAssets.push(path)
        } else if (fileName.match(/^assets\/.*\.(js|css)$/)) {
          featureChunks.push(path)
        }
      }

      const swSource = `// Auto-generated by vite build — do not edit manually
const CACHE_VERSION = 'v5';
const DATA_CACHE = 'wwe-data-' + CACHE_VERSION;
const SHELL_CACHE = 'wwe-shell-' + CACHE_VERSION;
const FEATURE_CACHE = 'wwe-features-' + CACHE_VERSION;

// Hashed data chunks — rarely change, use cache-first
const DATA_CHUNKS = ${JSON.stringify(dataChunks, null, 2)};

// App shell assets — index JS/CSS + vendor React
const SHELL_ASSETS = ${JSON.stringify([BASE, BASE + 'manifest.json', BASE + 'icon-192.svg', ...appShellAssets], null, 2)};

// Feature chunks — lazy-loaded components, pre-cached for offline
const FEATURE_CHUNKS = ${JSON.stringify(featureChunks, null, 2)};

// Pre-cache all assets on install
self.addEventListener('install', (event) => {
  event.waitUntil(
    Promise.all([
      caches.open(DATA_CACHE).then((cache) => cache.addAll(DATA_CHUNKS)),
      caches.open(SHELL_CACHE).then((cache) => cache.addAll(SHELL_ASSETS)),
      caches.open(FEATURE_CACHE).then((cache) => cache.addAll(FEATURE_CHUNKS)),
    ])
  );
  self.skipWaiting();
});

// Clean old caches on activate
self.addEventListener('activate', (event) => {
  const currentCaches = [DATA_CACHE, SHELL_CACHE, FEATURE_CACHE];
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(
        keys
          .filter((k) => !currentCaches.includes(k))
          .map((k) => caches.delete(k))
      )
    )
  );
  self.clients.claim();
});

// Fetch handler with dual strategy
self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET') return;
  if (!event.request.url.startsWith(self.location.origin)) return;

  const url = new URL(event.request.url);
  const isHashedAsset = url.pathname.match(/\\/assets\\/.+-[A-Za-z0-9_-]{8,}\\.(js|css)$/);

  if (isHashedAsset) {
    // Cache-first for all hashed assets — content-hashed filenames mean immutable
    event.respondWith(
      caches.match(event.request).then((cached) => {
        if (cached) return cached;
        return fetch(event.request).then((response) => {
          if (response.ok) {
            const clone = response.clone();
            // Store data chunks in DATA_CACHE, others in FEATURE_CACHE
            const cacheName = url.pathname.includes('/data-') ? DATA_CACHE : FEATURE_CACHE;
            caches.open(cacheName).then((cache) => cache.put(event.request, clone));
          }
          return response;
        });
      })
    );
  } else {
    // Network-first for app shell, navigation, and non-hashed resources
    event.respondWith(
      fetch(event.request)
        .then((response) => {
          if (response.ok) {
            const clone = response.clone();
            caches.open(SHELL_CACHE).then((cache) => cache.put(event.request, clone));
          }
          return response;
        })
        .catch(() => {
          return caches.match(event.request).then((cached) => {
            if (cached) return cached;
            // Offline navigation fallback: serve cached index.html for HTML requests
            if (event.request.mode === 'navigate') {
              return caches.match('${BASE}');
            }
            return undefined;
          });
        })
    );
  }
});
`
      // Emit sw.js as a build asset at the root (not in assets/)
      this.emitFile({
        type: 'asset',
        fileName: 'sw.js',
        source: swSource,
      })

      console.log(
        `[generate-sw] Emitted sw.js: ${dataChunks.length} data chunks, ${appShellAssets.length} shell assets, ${featureChunks.length} feature chunks`,
      )
    },
  }
}

// https://vite.dev/config/
export default defineConfig({
  base: BASE,
  plugins: [react(), generateServiceWorker()],
  server: {
    proxy: {
      '/api/anthropic': {
        target: 'https://api.anthropic.com',
        changeOrigin: true,
        rewrite: (path) => path.replace(/^\/api\/anthropic/, ''),
      },
    },
  },
  build: {
    rollupOptions: {
      output: {
        manualChunks: {
          // Large data files — split into parallel-loadable chunks
          'data-wiki': ['./src/data/wiki.js'],
          'data-personal': ['./src/data/personal.js'],
          'data-stats': ['./src/data/stats.js'],
          'data-wrestlers': ['./src/data/wrestlers.js'],
          'data-extra': ['./src/data/extra.js'],
          'data-themes': ['./src/data/themes.js'],
          'data-bio': ['./src/data/bio.js'],
          'data-images': ['./src/data/images.js'],
          'data-relationships': ['./src/data/relationships.js'],
          // Startup-critical data (small, needed by Header/filters)
          'data-misc': [
            './src/data/moves.js',
            './src/data/matchTypes.js',
            './src/data/brands.js',
          ],
          // Feature-specific data (lazy-loaded on demand)
          'data-promos': ['./src/data/promos.js'],
          'data-matches': ['./src/data/matches.js'],
          'data-trainers': ['./src/data/trainers.js'],
          // Vendor: React in its own chunk (cached independently)
          'vendor-react': ['react', 'react-dom'],
        },
      },
    },
  },
})
